### ISSUE TITLE
similar project for OBS

### ISSUE THREAD

**Issue by vpereira** [brett060102/ansible-container#24]
would be possible to merge or reuse what we have here https://github.com/openSUSE/ansible-obs/blob/master/Dockerfile ? Building the image on OBS give us the ability to keep the base image up to date.

**Comment by brett060102** [comment]
@vpereira I think I need a bit more context here. Do you mean the line
FROM registry.opensuse.org/obs/server/unstable/containers/containers/openbuildservice/ansible-obs-base:latest

From the Dockerfile reference above? If so, then no, the code is this repo is used to build the ansible-container container in OBS.
And the resulting container is self sufficient for installing getting ansible support on APL. 

If you mean something else, them I'm sorry, but I don't understand.

**Comment by rtamalin** [comment]
@vpereira Note that this project was developed to create a basic ansible workload container image, based upon the latest available Ansible version, that can be successfully used in ALP, enabling modification of the (ALP) container host, which is what the example playbooks packaged in the container are focused on.

So perhaps the repository name is a bit misleading, and it possible should be call ansible-container-for-alp.

Looking at your base container build in OBS (https://build.opensuse.org/package/view_file/OBS:Server:Unstable:Containers/ansible-obs-base/Dockerfile?expand=1 IIUC) you are pulling in many packages over an above what would be needed for purely Ansible operations.

If you are suggesting that this project's containers could be used as a basis for your project, well the goal of this container is to provide access to the latest Ansible versions, whereas your current base container is based upon the Ansible version available in SLE 15 SP3 + Leap 15.4 bits, meaning that your ansible version is 2.9.27 IIUC, which is very old and EOL for about 1 year now.

The Ansible 2.9 release stream was the last release predating the switch to the modern Ansible packaging approach, namely ansible-core provides the core Ansible and builtin components, and the ansible package is now more of a meta package that depends on a specific ansible-core release stream and pulls in relevant collections at specific versions that have been tested with that ansible-core version.

As @brett060102 suggested, if you wanted to clarify what you meant, that may help clasrifyu things and better focus any further discussions?

**Comment by vpereira** [comment]
Sorry, my idea was to have an ansible base container being built on b.o.o and then people build their specific images on top of that, avoiding many projects doing the same thing over and over again. Are we building the `ansible-container` on OBS?

**Comment by brett060102** [comment]
Yes, https://build.opensuse.org/package/show/SUSE:ALP:Workloads/ansible-container

**Comment by vpereira** [comment]
Great, thanks!
